name=CH572BlePeripheral
version=1.0.0
author=Deqing Sun
maintainer=https://github.com/deqingSun
sentence=BLE peripheral library for CH572
paragraph=BLE peripheral library for CH572 wrapper for CH572 TMOS BLE stack
category=Communication
url=
architectures=ch32v
precompiled=true
ldflags=-lCH572BLE_PERI
