name=SimpleUsbSerialWithKbd
version=1.0.0
author=Deqing Sun
maintainer=https://github.com/deqingSun
sentence=USB serial library for CH573 with keyboard support
paragraph=USB serial library for CH573 MCU with keyboard support
category=Communication
url=
architectures=ch32v
precompiled=true
