name=SimpleUsbSerial
version=1.0.0
author=Deqing Sun
maintainer=https://github.com/deqingSun
sentence=USB serial library for CH573
paragraph=USB serial library for CH573 MCU
category=Communication
url=
architectures=ch32v
precompiled=true
