name=CH572RF
version=1.0.0
author=Deqing Sun
maintainer=https://github.com/deqingSun
sentence=RF library for CH572
paragraph=RF library for CH572 wrapper for CH572 RF
category=Communication
url=
architectures=ch32v
precompiled=true
ldflags=-lCH57xRF
